import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { supabase } from '../../src/lib/supabase';
import { PROFILE_ROLES, type ProfileRole } from '../../src/user/types';

export default function OnboardingProfile(){ const theme=useAppTheme();const router=useRouter();const [name,setName]=useState('');const [role,setRole]=useState<ProfileRole|null>(null);const [company,setCompany]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState(''); async function save(){if(!supabase){setError('Account services are not configured yet.');return;}const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth/sign-in');return;}setBusy(true);setError('');const {error:e}=await supabase.from('profiles').upsert({id:user.id,display_name:name.trim()||null,role,company_name:company.trim()||null},{onConflict:'id'});setBusy(false);if(e){setError('Your profile could not be saved yet.');return;}router.replace('/');} return <Screen><ScrollView contentContainerStyle={styles.wrap}><Text style={[styles.eyebrow,{color:theme.colors.mutedText}]}>WELCOME TO TFN</Text><Text style={[styles.title,{color:theme.colors.text}]}>Tell us a little about you</Text><Text style={[styles.sub,{color:theme.colors.mutedText}]}>Optional details help us understand your place in the startup ecosystem. You can change them later.</Text><TextInput placeholder="Your name" placeholderTextColor={theme.colors.mutedText} value={name} onChangeText={setName} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/><Text style={[styles.label,{color:theme.colors.text}]}>Your role</Text><View style={styles.roles}>{PROFILE_ROLES.map(item=><Pressable key={item} onPress={()=>setRole(item)} style={[styles.role,{borderColor:role===item?theme.colors.text:theme.colors.border,backgroundColor:role===item?theme.colors.text:theme.colors.surface}]}><Text style={{color:role===item?theme.colors.inverseText:theme.colors.text,fontWeight:'700'}}>{item}</Text></Pressable>)}</View><TextInput placeholder="Company / startup (optional)" placeholderTextColor={theme.colors.mutedText} value={company} onChangeText={setCompany} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={save} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={{color:theme.colors.inverseText,fontWeight:'800'}}>{busy?'Saving…':'Continue to TFN'}</Text></Pressable></ScrollView></Screen> }
const styles=StyleSheet.create({wrap:{maxWidth:560,width:'100%',alignSelf:'center',paddingTop:42,paddingBottom:48},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:1.5},title:{fontSize:34,fontWeight:'800',marginTop:10},sub:{fontSize:16,lineHeight:24,marginTop:8,marginBottom:24},label:{fontWeight:'800',marginBottom:10},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:16,fontSize:16,marginBottom:14},roles:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:18},role:{paddingHorizontal:13,paddingVertical:11,borderWidth:1,borderRadius:20},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:4},error:{color:'#C62828',marginBottom:8}});
