import { useState } from 'react';
import { Link } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { supabase } from '../../src/lib/supabase';

export default function ForgotPassword(){ const theme=useAppTheme(); const [email,setEmail]=useState(''); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false); const [error,setError]=useState(''); async function submit(){if(!supabase){setError('Account services are not configured yet.');return;}if(!email.includes('@')){setError('Enter a valid email.');return;}setBusy(true);setError('');const {error:e}=await supabase.auth.resetPasswordForEmail(email.trim());setBusy(false);if(e){setError('We could not start password recovery. Please try again.');return;}setSent(true);} return <Screen><View style={styles.wrap}><Text style={[styles.title,{color:theme.colors.text}]}>Reset your password</Text><Text style={[styles.sub,{color:theme.colors.mutedText}]}>Enter your email and, if an account exists, we will send recovery instructions.</Text><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={theme.colors.mutedText} value={email} onChangeText={setEmail} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/>{sent?<Text style={[styles.success,{color:theme.colors.text}]}>If the address is registered, check your inbox for the recovery link.</Text>:null}{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy||sent} onPress={submit} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={[styles.buttonText,{color:theme.colors.inverseText}]}>{busy?'Sending…':'Send recovery link'}</Text></Pressable><Link href="/auth/sign-in" style={[styles.link,{color:theme.colors.text}]}>Back to sign in</Link></View></Screen> }
const styles=StyleSheet.create({wrap:{maxWidth:460,width:'100%',alignSelf:'center',paddingTop:48},title:{fontSize:32,fontWeight:'800'},sub:{fontSize:16,lineHeight:24,marginTop:8,marginBottom:28},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:16,fontSize:16,marginBottom:12},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center'},buttonText:{fontWeight:'800'},link:{fontWeight:'700',textAlign:'center',marginTop:20},success:{marginBottom:12},error:{color:'#C62828',marginBottom:8}});
