import { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader } from '../../src/components/AppHeader';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { supabase } from '../../src/lib/supabase';
import { PROFILE_INTERESTS, PROFILE_ROLES, type Profile, type ProfileGender, type ProfileRole } from '../../src/user/types';
import { getAvatarUrl, pickAndUploadAvatar } from '../../src/user/profile';

const GENDERS: ProfileGender[] = ['Male', 'Female', 'Prefer not to say'];

export default function EditProfile(){
  const theme=useAppTheme(); const router=useRouter(); const [profile,setProfile]=useState<Profile|null>(null); const [avatarUrl,setAvatarUrl]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(data){setProfile(data as Profile);setAvatarUrl(await getAvatarUrl(data.avatar_url));}})()},[]);
  if(!profile)return <Screen><AppHeader title="Edit profile" back/><Text style={[styles.loading,{color:theme.colors.mutedText}]}>Loading profile…</Text></Screen>;
  function update(field:keyof Profile,value:unknown){setProfile(current=>current?{...current,[field]:value}:current);}
  async function uploadAvatar(){try{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const path=await pickAndUploadAvatar(user.id);if(path){update('avatar_url',path);setAvatarUrl(await getAvatarUrl(path));}}catch(e){setMessage(e instanceof Error?e.message:'Could not upload photo.');}}
  async function save(){if(!supabase||!profile)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;setBusy(true);setMessage('');const {error}=await supabase.from('profiles').update({...profile,updated_at:new Date().toISOString()}).eq('id',user.id);setBusy(false);if(error){setMessage('Could not save your profile.');return;}setMessage('Profile saved.');}
  return <Screen><AppHeader title="Edit profile" back/><ScrollView contentContainerStyle={styles.wrap}>
    <Pressable onPress={uploadAvatar} style={styles.avatarButton}>{avatarUrl?<Image source={{uri:avatarUrl}} style={styles.avatar}/>:<Text style={[styles.avatarText,{color:theme.colors.text}]}>Add photo</Text>}</Pressable>
    <Text style={[styles.label,{color:theme.colors.text}]}>Name</Text><TextInput value={profile.display_name??''} onChangeText={value=>update('display_name',value)} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/>
    <Text style={[styles.label,{color:theme.colors.text}]}>Gender</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{GENDERS.map(item=><Pressable key={item} onPress={()=>update('gender',item)} style={[styles.chip,{borderColor:profile.gender===item?theme.colors.text:theme.colors.border,backgroundColor:profile.gender===item?theme.colors.text:theme.colors.surface}]}><Text style={{color:profile.gender===item?theme.colors.inverseText:theme.colors.text,fontWeight:'700'}}>{item}</Text></Pressable>)}</ScrollView>
    <Text style={[styles.label,{color:theme.colors.text}]}>Role</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{PROFILE_ROLES.map(item=><Pressable key={item} onPress={()=>update('role',item as ProfileRole)} style={[styles.chip,{borderColor:profile.role===item?theme.colors.text:theme.colors.border,backgroundColor:profile.role===item?theme.colors.text:theme.colors.surface}]}><Text style={{color:profile.role===item?theme.colors.inverseText:theme.colors.text,fontWeight:'700'}}>{item}</Text></Pressable>)}</ScrollView>
    {(['phone_number','company_name','job_title','industry','location','website','linkedin_url','instagram_url','bio'] as const).map(field=><TextInput key={field} value={String(profile[field]??'')} onChangeText={value=>update(field,value)} multiline={field==='bio'} placeholder={field.replaceAll('_',' ')} placeholderTextColor={theme.colors.mutedText} autoCapitalize={field.includes('url')?'none':'sentences'} style={[field==='bio'?styles.textarea:styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/>)}
    <Text style={[styles.label,{color:theme.colors.text}]}>Interests</Text><View style={styles.chips}>{PROFILE_INTERESTS.map(item=><Pressable key={item} onPress={()=>update('interests',profile.interests.includes(item)?profile.interests.filter(x=>x!==item):[...profile.interests,item])} style={[styles.chip,{borderColor:profile.interests.includes(item)?theme.colors.accent:theme.colors.border,backgroundColor:profile.interests.includes(item)?theme.colors.accent:theme.colors.surface}]}><Text style={{color:profile.interests.includes(item)?theme.colors.inverseText:theme.colors.text,fontWeight:'700'}}>{item}</Text></Pressable>)}</View>
    {message?<Text style={[styles.message,{color:theme.colors.mutedText}]}>{message}</Text>:null}<Pressable disabled={busy} onPress={save} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={{color:theme.colors.inverseText,fontWeight:'800'}}>{busy?'Saving…':'Save changes'}</Text></Pressable><Pressable onPress={()=>router.back()} style={styles.cancel}><Text style={{color:theme.colors.text,fontWeight:'700'}}>Done</Text></Pressable>
  </ScrollView></Screen>
}
const styles=StyleSheet.create({wrap:{maxWidth:620,width:'100%',alignSelf:'center',padding:20,paddingBottom:48},loading:{padding:20},avatarButton:{alignSelf:'center',width:104,height:104,borderRadius:52,borderWidth:1,borderColor:'#D0D0D0',alignItems:'center',justifyContent:'center',marginBottom:18},avatar:{width:102,height:102,borderRadius:51},avatarText:{fontWeight:'800'},label:{fontWeight:'800',marginBottom:8,marginTop:10},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:16,fontSize:16,marginBottom:12},textarea:{minHeight:100,borderWidth:1,borderRadius:12,padding:14,fontSize:16,marginBottom:12,textAlignVertical:'top'},row:{gap:8,paddingBottom:12},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,paddingBottom:12},chip:{paddingHorizontal:13,paddingVertical:11,borderWidth:1,borderRadius:20},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center'},cancel:{alignItems:'center',padding:18},message:{marginBottom:10}});
