import { useEffect, useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { Screen } from '../../src/components/Screen';
import { AppHeader } from '../../src/components/AppHeader';
import { useAppTheme } from '../../src/theme';
import { supabase } from '../../src/lib/supabase';
import { PROFILE_ROLES, type ProfileRole } from '../../src/user/types';

export default function EditProfile(){const theme=useAppTheme();const router=useRouter();const [name,setName]=useState('');const [company,setCompany]=useState('');const [role,setRole]=useState<ProfileRole|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');useEffect(()=>{supabase?.auth.getUser().then(async({data})=>{if(!data.user)return;const {data:p}=await supabase!.from('profiles').select('display_name,company_name,role').eq('id',data.user.id).maybeSingle();if(p){setName(p.display_name??'');setCompany(p.company_name??'');setRole(p.role);}})},[]);async function save(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;setBusy(true);setMessage('');const {error}=await supabase.from('profiles').update({display_name:name.trim()||null,company_name:company.trim()||null,role}).eq('id',user.id);setBusy(false);if(error){setMessage('Could not save your profile.');return;}setMessage('Profile saved.');}return <Screen><AppHeader title="Edit profile" back/><ScrollView contentContainerStyle={styles.wrap}><Text style={[styles.label,{color:theme.colors.text}]}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={theme.colors.mutedText} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/><Text style={[styles.label,{color:theme.colors.text}]}>Role</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.roles}>{PROFILE_ROLES.map(item=><Pressable key={item} onPress={()=>setRole(item)} style={[styles.role,{borderColor:role===item?theme.colors.text:theme.colors.border,backgroundColor:role===item?theme.colors.text:theme.colors.surface}]}><Text style={{color:role===item?theme.colors.inverseText:theme.colors.text,fontWeight:'700'}}>{item}</Text></Pressable>)}</ScrollView><Text style={[styles.label,{color:theme.colors.text}]}>Company / startup</Text><TextInput value={company} onChangeText={setCompany} placeholder="Optional" placeholderTextColor={theme.colors.mutedText} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}/>{message?<Text style={{color:theme.colors.mutedText,marginBottom:12}}>{message}</Text>:null}<Pressable disabled={busy} onPress={async()=>{await save();}} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={{color:theme.colors.inverseText,fontWeight:'800'}}>{busy?'Saving…':'Save changes'}</Text></Pressable><Pressable onPress={()=>router.back()} style={styles.cancel}><Text style={{color:theme.colors.text,fontWeight:'700'}}>Done</Text></Pressable></ScrollView></Screen>}
const styles=StyleSheet.create({wrap:{maxWidth:560,width:'100%',alignSelf:'center',padding:20,paddingBottom:48},label:{fontWeight:'800',marginBottom:8,marginTop:8},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:16,fontSize:16,marginBottom:14},roles:{gap:8,paddingBottom:14},role:{paddingHorizontal:13,paddingVertical:11,borderWidth:1,borderRadius:20},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center'},cancel:{alignItems:'center',padding:18}});
