import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '../../src/components/AppHeader';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { getMyInterests, saveMyInterests, TFN_INTERESTS, type TfnInterest } from '../../src/user/interests';

export default function Interests() {
  const theme = useAppTheme(); const [selected, setSelected] = useState<TfnInterest[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setSelected(await getMyInterests()); } catch { setError('Could not load your interests. Please try again.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  function toggle(item: TfnInterest) { setMessage(''); setSelected((current) => current.some((x) => x.type === item.type && x.key === item.key) ? current.filter((x) => !(x.type === item.type && x.key === item.key)) : [...current, item]); }
  async function save() { setBusy(true); setError(''); setMessage(''); try { await saveMyInterests(selected); setMessage('Your interests have been saved.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save your interests. Please try again.'); } finally { setBusy(false); } }
  if (loading) return <Screen><AppHeader title="Interests" back /><View style={styles.state}><Text style={{ color: theme.colors.mutedText }}>Loading your interests…</Text></View></Screen>;
  return <Screen><AppHeader title="Interests" back /><ScrollView contentContainerStyle={styles.wrap}><Text style={[styles.title, { color: theme.colors.text }]}>Personalize TFN</Text><Text style={[styles.body, { color: theme.colors.mutedText }]}>Choose the topics, industries and startup stories you care about. These preferences are private and help TFN make future recommendations more relevant.</Text><Text style={[styles.count, { color: theme.colors.mutedText }]}>{selected.length} selected · Choose 3–15 when setting up personalization</Text><View style={styles.chips}>{TFN_INTERESTS.map((item) => { const active = selected.some((x) => x.type === item.type && x.key === item.key); return <Pressable key={`${item.type}:${item.key}`} accessibilityRole="checkbox" accessibilityState={{ checked: active }} accessibilityLabel={`${item.label}, ${active ? 'selected' : 'not selected'}`} onPress={() => toggle(item)} style={[styles.chip, { borderColor: active ? theme.colors.accent : theme.colors.border, backgroundColor: active ? theme.colors.accent : theme.colors.surface }]}><Text style={{ color: active ? theme.colors.inverseText : theme.colors.text, fontWeight: '700' }}>{active ? '✓ ' : ''}{item.label}</Text></Pressable>; })}</View>{error ? <Text style={[styles.error, { color: '#C62828' }]}>{error}</Text> : null}{message ? <Text style={[styles.message, { color: theme.colors.mutedText }]}>{message}</Text> : null}<Pressable disabled={busy} accessibilityRole="button" accessibilityLabel="Save interests" onPress={save} style={[styles.button, { backgroundColor: theme.colors.accent, opacity: busy ? 0.65 : 1 }]}><Text style={{ color: theme.colors.inverseText, fontWeight: '800' }}>{busy ? 'Saving…' : 'Save interests'}</Text></Pressable></ScrollView></Screen>;
}
const styles = StyleSheet.create({ wrap: { maxWidth: 620, width: '100%', alignSelf: 'center', padding: 20, paddingBottom: 48 }, state: { flex: 1, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 32, fontWeight: '800' }, body: { fontSize: 16, lineHeight: 24, marginTop: 10, marginBottom: 12 }, count: { fontSize: 13, fontWeight: '700', marginBottom: 18 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 44, paddingHorizontal: 13, paddingVertical: 11, borderWidth: 1, borderRadius: 22, justifyContent: 'center' }, button: { height: 52, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 28 }, error: { marginTop: 14, lineHeight: 20 }, message: { marginTop: 14, lineHeight: 20 } });
