import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader } from '../../src/components/AppHeader';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { supabase } from '../../src/lib/supabase';
import { useAuth } from '../../src/user/auth';

export default function Settings(){const theme=useAppTheme();const router=useRouter();const {signOut}=useAuth();const [consent,setConsent]=useState(true);async function saveConsent(next:boolean){setConsent(next);if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('profiles').update({personalization_consent:next}).eq('id',user.id);}function confirmDelete(){Alert.alert('Delete your TFN account?','This permanently removes your account data. This action cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{if(!supabase)return;const {error}=await supabase.functions.invoke('delete-account');if(error){Alert.alert('Could not delete account','Account deletion needs the secure TFN deletion function to be configured.');return;}await signOut();router.replace('/');}}]);}return <Screen><AppHeader title="Account & privacy" back/><View style={styles.wrap}><Text style={[styles.heading,{color:theme.colors.text}]}>Privacy</Text><Text style={[styles.body,{color:theme.colors.mutedText}]}>Your profile is private by default. TFN can use information you provide to improve your experience only when you allow personalization.</Text><View style={styles.row}><View style={{flex:1}}><Text style={[styles.rowTitle,{color:theme.colors.text}]}>Personalization</Text><Text style={[styles.body,{color:theme.colors.mutedText}]}>Allow TFN to use account preferences and future preference signals to personalize content.</Text></View><Switch value={consent} onValueChange={saveConsent}/></View><Text style={[styles.heading,{color:theme.colors.text}]}>Account</Text><Pressable onPress={signOut} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Sign out</Text></Pressable><Pressable onPress={confirmDelete} style={styles.delete}><Text style={{color:'#C62828',fontWeight:'800'}}>Delete account</Text></Pressable></View></Screen>}
const styles=StyleSheet.create({wrap:{maxWidth:600,width:'100%',alignSelf:'center',padding:20},heading:{fontSize:22,fontWeight:'800',marginTop:12,marginBottom:10},body:{fontSize:15,lineHeight:22},row:{flexDirection:'row',alignItems:'center',gap:16,paddingVertical:18,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#D0D0D0'},rowTitle:{fontSize:16,fontWeight:'800',marginBottom:4},secondary:{height:52,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:10},delete:{alignItems:'center',padding:20,marginTop:12}});
