import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader } from '../../src/components/AppHeader';
import { ArticleCard } from '../../src/components/ArticleCard';
import { Screen } from '../../src/components/Screen';
import { getArticles } from '../../src/content';
import { enrichHomeContent, getHomeContent, type HomeContent } from '../../src/content/home';
import { useAppTheme } from '../../src/theme';

function Section({title,children}:{title:string;children:ReactNode}){const theme=useAppTheme();return <View style={styles.section}><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>{title}</Text>{children}</View>}
function Skeleton({large=false}:{large?:boolean}){const theme=useAppTheme();return <View style={[styles.skeleton,{backgroundColor:theme.colors.surface},large&&styles.skeletonLarge]}/>}

export default function HomeScreen(){const theme=useAppTheme();const router=useRouter();const[data,setData]=useState<HomeContent>();const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[loadingMore,setLoadingMore]=useState(false);const[page,setPage]=useState(1);const[hasMore,setHasMore]=useState(true);const[error,setError]=useState(false);
const load=useCallback(async(refresh=false)=>{try{setError(false);if(refresh)setRefreshing(true);else setLoading(true);const primary=await getHomeContent();setData(primary);setPage(1);setHasMore(true);setLoading(false);setRefreshing(false);const enriched=await enrichHomeContent(primary);setData(enriched)}catch{setError(true);setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);
const loadMore=useCallback(async()=>{if(!data||loadingMore||!hasMore)return;try{setLoadingMore(true);const next=page+1;const result=await getArticles({page:next,perPage:8});setData(current=>current?{...current,latest:[...current.latest,...result.items]}:current);setPage(next);setHasMore(result.pagination.hasNextPage)}finally{setLoadingMore(false)}},[data,hasMore,loadingMore,page]);
const open=(id:number)=>router.push({pathname:'/article/[id]',params:{id:String(id)}});const horizontal=(title:string,items:HomeContent['latest'])=>items.length?<Section title={title}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}>{items.slice(0,5).map(a=><View key={a.id} style={styles.horizontalCard}><ArticleCard article={a} variant="compact" onPress={()=>open(a.id)}/></View>)}</ScrollView></Section>:null;
return <Screen scroll={false} padding={false}><AppHeader/><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={theme.colors.icon}/>} onScroll={({nativeEvent})=>{const{layoutMeasurement,contentOffset,contentSize}=nativeEvent;if(layoutMeasurement.height+contentOffset.y>=contentSize.height-700)void loadMore()}} scrollEventThrottle={250}>
{loading?<><Skeleton large/><Skeleton/><Skeleton/><Skeleton/></>:error&&!data?<View style={styles.state}><Text style={[styles.stateTitle,{color:theme.colors.text}]}>TFN is temporarily unavailable</Text><Text style={[styles.stateBody,{color:theme.colors.mutedText}]}>We could not load the latest stories.</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={[styles.retry,{backgroundColor:theme.colors.text}]}><Text style={{color:theme.colors.inverseText,fontWeight:'700'}}>Retry</Text></Pressable></View>:data?<>{data.featured?<Section title="Featured"><ArticleCard article={data.featured} variant="featured" onPress={()=>open(data.featured!.id)}/></Section>:null}
{horizontal('For You',data.forYou)}{horizontal('Startup Stories',data.startupStories)}{horizontal('Funding',data.funding)}{horizontal('Founder Stories',data.founderStories)}{horizontal('Technology & AI',[...data.ai,...data.technology])}
<Section title="Trending"><Pressable accessibilityRole="button" accessibilityLabel="Open Trending" onPress={()=>router.push('/(tabs)/discover')} style={[styles.trending,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><View style={styles.trendingCopy}><Text style={[styles.trendingTitle,{color:theme.colors.text}]}>What the ecosystem is talking about</Text><Text style={[styles.trendingBody,{color:theme.colors.mutedText}]}>Open Discover for the broader TFN content stream.</Text></View><Text style={[styles.arrow,{color:theme.colors.text}]}>›</Text></Pressable></Section>
<Section title="Latest">{data.latest.map((a,i)=><ArticleCard key={String(a.id)+'-'+String(i)} article={a} onPress={()=>open(a.id)}/>)}{loadingMore?<ActivityIndicator style={styles.loader} color={theme.colors.icon}/>:null}{!hasMore?<Text style={[styles.end,{color:theme.colors.mutedText}]}>You’re all caught up.</Text>:null}</Section>
</>:null}</ScrollView></Screen>}
const styles=StyleSheet.create({content:{paddingHorizontal:18,paddingTop:18,paddingBottom:36},section:{marginBottom:24},sectionTitle:{fontSize:22,lineHeight:28,fontWeight:'800',marginBottom:12},horizontal:{gap:12,paddingBottom:2},horizontalCard:{width:300},skeleton:{height:190,borderRadius:16,marginBottom:12,opacity:.75},skeletonLarge:{height:300},state:{paddingVertical:90,alignItems:'center'},stateTitle:{fontSize:20,fontWeight:'800',textAlign:'center'},stateBody:{marginTop:8,textAlign:'center'},retry:{marginTop:18,paddingHorizontal:22,paddingVertical:12,borderRadius:999},trending:{borderWidth:StyleSheet.hairlineWidth,borderRadius:16,padding:16,flexDirection:'row',alignItems:'center'},trendingCopy:{flex:1},trendingTitle:{fontSize:16,fontWeight:'800'},trendingBody:{fontSize:13,lineHeight:19,marginTop:5},arrow:{fontSize:30,paddingLeft:12},loader:{marginVertical:10},end:{textAlign:'center',fontSize:13,marginTop:6}});
