import { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader } from '../../src/components/AppHeader';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { useAuth } from '../../src/user/auth';
import { supabase } from '../../src/lib/supabase';
import { getAvatarUrl } from '../../src/user/profile';
import type { Profile } from '../../src/user/types';

export default function ProfileScreen(){
  const theme=useAppTheme();const router=useRouter();const {user,state,signOut}=useAuth();const [profile,setProfile]=useState<Profile|null>(null);const [avatar,setAvatar]=useState<string|null>(null);
  useEffect(()=>{if(!user||!supabase)return;(async()=>{const {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(data){setProfile(data as Profile);setAvatar(await getAvatarUrl(data.avatar_url));}})()},[user]);
  if(state==='loading')return <Screen><AppHeader title="Profile"/><Text style={[styles.body,{color:theme.colors.mutedText}]}>Restoring your account…</Text></Screen>;
  if(!user)return <Screen><AppHeader title="Profile"/><View style={styles.center}><Text style={[styles.title,{color:theme.colors.text}]}>Your TFN account</Text><Text style={[styles.body,{color:theme.colors.mutedText}]}>Create an account to personalize your TFN experience. Public stories remain available without signing in.</Text><Pressable onPress={()=>router.push('/auth/sign-in')} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={{color:theme.colors.inverseText,fontWeight:'800'}}>Sign in</Text></Pressable><Pressable onPress={()=>router.push('/auth/create-account')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Create account</Text></Pressable></View></Screen>;
  return <Screen><AppHeader title="Profile"/><ScrollView contentContainerStyle={styles.wrap}>
    <View style={styles.hero}>{avatar?<Image source={{uri:avatar}} style={styles.avatar}/>:<View style={[styles.avatarPlaceholder,{borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}><Text style={{color:theme.colors.mutedText,fontWeight:'800'}}>TFN</Text></View>}<Text style={[styles.title,{color:theme.colors.text}]}>{profile?.display_name||'TFN member'}</Text><Text style={[styles.role,{color:theme.colors.mutedText}]}>{profile?.role||'Role not added yet'}</Text>{profile?.company_name?<Text style={[styles.body,{color:theme.colors.text}]}>{profile.company_name}{profile.job_title?` · ${profile.job_title}`:''}</Text>:null}</View>
    {profile?.bio?<Text style={[styles.bio,{color:theme.colors.text}]}>{profile.bio}</Text>:null}
    <View style={[styles.infoCard,{borderColor:theme.colors.border,backgroundColor:theme.colors.surface}]}>{[['Location',profile?.location],['Industry',profile?.industry],['Website',profile?.website],['LinkedIn',profile?.linkedin_url],['Instagram',profile?.instagram_url]].map(([label,value])=>value?<View key={String(label)} style={styles.infoRow}><Text style={[styles.infoLabel,{color:theme.colors.mutedText}]}>{label}</Text><Text style={[styles.infoValue,{color:theme.colors.text}]}>{value}</Text></View>:null)}</View>
    {profile?.interests?.length?<><Text style={[styles.sectionTitle,{color:theme.colors.text}]}>Interests</Text><View style={styles.chips}>{profile.interests.map(item=><View key={item} style={[styles.chip,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'700'}}>{item}</Text></View>)}</View></>:null}
    <Pressable onPress={()=>router.push('/account/edit-profile')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Edit profile</Text></Pressable><Pressable onPress={()=>router.push('/account/settings')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Account & privacy</Text></Pressable><Pressable onPress={()=>router.push('/account/interests')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Manage interests</Text></Pressable><Pressable onPress={signOut} style={styles.signout}><Text style={{color:'#C62828',fontWeight:'800'}}>Sign out</Text></Pressable>
  </ScrollView></Screen>
}
const styles=StyleSheet.create({wrap:{maxWidth:620,width:'100%',alignSelf:'center',padding:20,paddingBottom:48},center:{maxWidth:560,width:'100%',alignSelf:'center',padding:20,paddingTop:50},hero:{alignItems:'center',paddingTop:12},avatar:{width:104,height:104,borderRadius:52,marginBottom:16},avatarPlaceholder:{width:104,height:104,borderRadius:52,borderWidth:1,alignItems:'center',justifyContent:'center',marginBottom:16},title:{fontSize:32,fontWeight:'800',textAlign:'center'},role:{fontSize:16,marginTop:6,textAlign:'center'},body:{fontSize:16,lineHeight:24,marginTop:8,textAlign:'center'},bio:{fontSize:16,lineHeight:24,marginTop:20},infoCard:{borderWidth:1,borderRadius:16,padding:16,marginTop:20},infoRow:{marginBottom:12},infoLabel:{fontSize:12,fontWeight:'800',textTransform:'uppercase',letterSpacing:1},infoValue:{fontSize:15,marginTop:4},sectionTitle:{fontSize:20,fontWeight:'800',marginTop:24,marginBottom:10},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderWidth:1,borderRadius:20},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:24},secondary:{height:52,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:12},signout:{alignItems:'center',padding:20,marginTop:18}});
