import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppHeader } from '../../src/components/AppHeader';
import { Screen } from '../../src/components/Screen';
import { useAppTheme } from '../../src/theme';
import { useAuth } from '../../src/user/auth';
import { supabase } from '../../src/lib/supabase';
import type { Profile } from '../../src/user/types';

export default function ProfileScreen(){const theme=useAppTheme();const router=useRouter();const {user,state,signOut}=useAuth();const [profile,setProfile]=useState<Profile|null>(null);useEffect(()=>{if(!user||!supabase)return;supabase.from('profiles').select('*').eq('id',user.id).maybeSingle().then(({data})=>setProfile(data as Profile|null));},[user]);if(state==='loading')return <Screen><AppHeader title="Profile"/><Text style={[styles.body,{color:theme.colors.mutedText}]}>Restoring your account…</Text></Screen>;if(!user)return <Screen><AppHeader title="Profile"/><View style={styles.center}><Text style={[styles.title,{color:theme.colors.text}]}>Your TFN account</Text><Text style={[styles.body,{color:theme.colors.mutedText}]}>Create an account to personalize your TFN experience. Public stories remain available without signing in.</Text><Pressable onPress={()=>router.push('/auth/sign-in')} style={[styles.button,{backgroundColor:theme.colors.accent}]}><Text style={{color:theme.colors.inverseText,fontWeight:'800'}}>Sign in</Text></Pressable><Pressable onPress={()=>router.push('/auth/create-account')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Create account</Text></Pressable></View></Screen>;return <Screen><AppHeader title="Profile"/><View style={styles.wrap}><Text style={[styles.title,{color:theme.colors.text}]}>{profile?.display_name||'TFN member'}</Text><Text style={[styles.role,{color:theme.colors.mutedText}]}>{profile?.role||'Role not added yet'}</Text>{profile?.company_name?<Text style={[styles.body,{color:theme.colors.text}]}>{profile.company_name}</Text>:null}<Pressable onPress={()=>router.push('/account/edit-profile')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Edit profile</Text></Pressable><Pressable onPress={()=>router.push('/account/settings')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Account & privacy</Text></Pressable><Pressable onPress={()=>router.push('/account/interests')} style={[styles.secondary,{borderColor:theme.colors.border}]}><Text style={{color:theme.colors.text,fontWeight:'800'}}>Interests</Text></Pressable><Pressable onPress={signOut} style={styles.signout}><Text style={{color:'#C62828',fontWeight:'800'}}>Sign out</Text></Pressable></View></Screen>}
const styles=StyleSheet.create({wrap:{maxWidth:560,width:'100%',alignSelf:'center',padding:20},center:{maxWidth:560,width:'100%',alignSelf:'center',padding:20,paddingTop:50},title:{fontSize:32,fontWeight:'800'},role:{fontSize:16,marginTop:6},body:{fontSize:16,lineHeight:24,marginTop:10},button:{height:52,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:24},secondary:{height:52,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:12},signout:{alignItems:'center',padding:20,marginTop:18}});
